"use strict";

const path = require("path");
const os = require("os");

const DIRECT_PROTOCOLS = [
  "SSH",
  "OSSH",
  "TLS-OSSH",
  "UNFRONTED-MEEK-OSSH",
  "UNFRONTED-MEEK-HTTPS-OSSH",
  "UNFRONTED-MEEK-SESSION-TICKET-OSSH",
  "FRONTED-MEEK-OSSH",
  "FRONTED-MEEK-HTTP-OSSH",
  "QUIC-OSSH",
  "FRONTED-MEEK-QUIC-OSSH",
  "TAPDANCE-OSSH",
  "CONJURE-OSSH",
  "SHADOWSOCKS-OSSH",
];

const CONDUIT_PROTOCOLS = [
  "INPROXY-WEBRTC-SSH",
  "INPROXY-WEBRTC-OSSH",
  "INPROXY-WEBRTC-TLS-OSSH",
  "INPROXY-WEBRTC-UNFRONTED-MEEK-OSSH",
  "INPROXY-WEBRTC-UNFRONTED-MEEK-HTTPS-OSSH",
  "INPROXY-WEBRTC-UNFRONTED-MEEK-SESSION-TICKET-OSSH",
  "INPROXY-WEBRTC-FRONTED-MEEK-OSSH",
  "INPROXY-WEBRTC-FRONTED-MEEK-HTTP-OSSH",
  "INPROXY-WEBRTC-QUIC-OSSH",
  "INPROXY-WEBRTC-FRONTED-MEEK-QUIC-OSSH",
  "INPROXY-WEBRTC-SHADOWSOCKS-OSSH",
];

const PSIPHON_BIN = "psiphon-tunnel-core-x86_64";
const DEFAULT_CONFIG_DIR = path.join(os.homedir(), ".config", "psiphon-cli");
const STATS_UPDATE_MS = 2000;

const FILES = {
  CONFIG: "psiphon.config",
  STATS: "stats.json",
  PID: "psiphon.pid",
};

module.exports = {
  DIRECT_PROTOCOLS,
  CONDUIT_PROTOCOLS,
  PSIPHON_BIN,
  DEFAULT_CONFIG_DIR,
  STATS_UPDATE_MS,
  FILES,
};
